# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QLabel,
    QLineEdit, QPushButton, QSizePolicy, QStackedWidget,
    QWidget)

class Ui_TTS(object):
    def setupUi(self, TTS):
        if not TTS.objectName():
            TTS.setObjectName(u"TTS")
        TTS.setEnabled(True)
        TTS.resize(1215, 699)
        self.MainStack = QStackedWidget(TTS)
        self.MainStack.setObjectName(u"MainStack")
        self.MainStack.setGeometry(QRect(0, 0, 1211, 691))
        self.ImportPage = QWidget()
        self.ImportPage.setObjectName(u"ImportPage")
        self.label = QLabel(self.ImportPage)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(480, 40, 211, 71))
        font = QFont()
        font.setFamilies([u"Cascadia Mono"])
        font.setPointSize(36)
        font.setBold(True)
        self.label.setFont(font)
        self.label_3 = QLabel(self.ImportPage)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(110, 177, 311, 51))
        font1 = QFont()
        font1.setFamilies([u"Cascadia Code"])
        font1.setPointSize(20)
        font1.setBold(True)
        self.label_3.setFont(font1)
        self.txtMovieLocation = QLineEdit(self.ImportPage)
        self.txtMovieLocation.setObjectName(u"txtMovieLocation")
        self.txtMovieLocation.setGeometry(QRect(110, 247, 361, 31))
        font2 = QFont()
        font2.setFamilies([u"Cascadia Code"])
        font2.setPointSize(10)
        self.txtMovieLocation.setFont(font2)
        self.line = QFrame(self.ImportPage)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(24, 670, 1162, 20))
        self.line.setFrameShadow(QFrame.Plain)
        self.line.setLineWidth(5)
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line_2 = QFrame(self.ImportPage)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(10, 20, 31, 661))
        self.line_2.setFrameShadow(QFrame.Plain)
        self.line_2.setLineWidth(5)
        self.line_2.setFrameShape(QFrame.Shape.VLine)
        self.line_3 = QFrame(self.ImportPage)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(1170, 20, 31, 661))
        self.line_3.setFrameShadow(QFrame.Plain)
        self.line_3.setLineWidth(5)
        self.line_3.setFrameShape(QFrame.Shape.VLine)
        self.line_4 = QFrame(self.ImportPage)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(24, 10, 1162, 20))
        self.line_4.setFrameShadow(QFrame.Plain)
        self.line_4.setLineWidth(5)
        self.line_4.setFrameShape(QFrame.Shape.HLine)
        self.btMovieBrowse = QPushButton(self.ImportPage)
        self.btMovieBrowse.setObjectName(u"btMovieBrowse")
        self.btMovieBrowse.setGeometry(QRect(480, 247, 101, 31))
        font3 = QFont()
        font3.setFamilies([u"Cascadia Code"])
        font3.setPointSize(16)
        self.btMovieBrowse.setFont(font3)
        self.chkbxMovies = QCheckBox(self.ImportPage)
        self.chkbxMovies.setObjectName(u"chkbxMovies")
        self.chkbxMovies.setGeometry(QRect(80, 190, 31, 26))
        self.label_4 = QLabel(self.ImportPage)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(110, 225, 121, 21))
        font4 = QFont()
        font4.setFamilies([u"Cascadia Code"])
        font4.setPointSize(12)
        font4.setBold(True)
        self.label_4.setFont(font4)
        self.label_5 = QLabel(self.ImportPage)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(110, 314, 101, 51))
        self.label_5.setFont(font1)
        self.btnAnimeBrowse = QPushButton(self.ImportPage)
        self.btnAnimeBrowse.setObjectName(u"btnAnimeBrowse")
        self.btnAnimeBrowse.setGeometry(QRect(480, 384, 101, 31))
        self.btnAnimeBrowse.setFont(font3)
        self.txtAnimeLocation = QLineEdit(self.ImportPage)
        self.txtAnimeLocation.setObjectName(u"txtAnimeLocation")
        self.txtAnimeLocation.setGeometry(QRect(110, 384, 361, 31))
        self.txtAnimeLocation.setFont(font2)
        self.label_6 = QLabel(self.ImportPage)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(110, 362, 121, 21))
        self.label_6.setFont(font4)
        self.chkbxAnime = QCheckBox(self.ImportPage)
        self.chkbxAnime.setObjectName(u"chkbxAnime")
        self.chkbxAnime.setGeometry(QRect(80, 327, 31, 26))
        self.txtCodingLocation = QLineEdit(self.ImportPage)
        self.txtCodingLocation.setObjectName(u"txtCodingLocation")
        self.txtCodingLocation.setGeometry(QRect(110, 527, 361, 31))
        self.txtCodingLocation.setFont(font2)
        self.chkbxCoding = QCheckBox(self.ImportPage)
        self.chkbxCoding.setObjectName(u"chkbxCoding")
        self.chkbxCoding.setGeometry(QRect(80, 470, 31, 26))
        self.label_7 = QLabel(self.ImportPage)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(110, 457, 121, 51))
        self.label_7.setFont(font1)
        self.btnCodingBrowse = QPushButton(self.ImportPage)
        self.btnCodingBrowse.setObjectName(u"btnCodingBrowse")
        self.btnCodingBrowse.setGeometry(QRect(480, 527, 101, 31))
        self.btnCodingBrowse.setFont(font3)
        self.label_8 = QLabel(self.ImportPage)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(110, 505, 121, 21))
        self.label_8.setFont(font4)
        self.line_5 = QFrame(self.ImportPage)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(640, 150, 31, 461))
        self.line_5.setFrameShadow(QFrame.Plain)
        self.line_5.setLineWidth(5)
        self.line_5.setFrameShape(QFrame.Shape.VLine)
        self.txtLogLocation = QLineEdit(self.ImportPage)
        self.txtLogLocation.setObjectName(u"txtLogLocation")
        self.txtLogLocation.setGeometry(QRect(730, 432, 421, 31))
        self.txtLogLocation.setFont(font2)
        self.chkbxLog = QCheckBox(self.ImportPage)
        self.chkbxLog.setObjectName(u"chkbxLog")
        self.chkbxLog.setGeometry(QRect(700, 375, 31, 26))
        self.label_9 = QLabel(self.ImportPage)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(730, 362, 231, 51))
        self.label_9.setFont(font1)
        self.btnLogBrowse = QPushButton(self.ImportPage)
        self.btnLogBrowse.setObjectName(u"btnLogBrowse")
        self.btnLogBrowse.setGeometry(QRect(1050, 470, 101, 31))
        self.btnLogBrowse.setFont(font3)
        self.label_10 = QLabel(self.ImportPage)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(730, 410, 121, 21))
        self.label_10.setFont(font4)
        self.btnImport = QPushButton(self.ImportPage)
        self.btnImport.setObjectName(u"btnImport")
        self.btnImport.setGeometry(QRect(1020, 610, 131, 51))
        font5 = QFont()
        font5.setFamilies([u"Cascadia Code"])
        font5.setPointSize(18)
        font5.setBold(True)
        self.btnImport.setFont(font5)
        self.label_11 = QLabel(self.ImportPage)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(700, 200, 491, 111))
        font6 = QFont()
        font6.setFamilies([u"Cascadia Code"])
        self.label_11.setFont(font6)
        self.pushButton = QPushButton(self.ImportPage)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(360, 193, 31, 21))
        icon = QIcon()
        icon.addFile(u"src/info.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setFlat(True)
        self.pushButton_2 = QPushButton(self.ImportPage)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(190, 330, 31, 21))
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setFlat(True)
        self.pushButton_3 = QPushButton(self.ImportPage)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(210, 474, 31, 21))
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setFlat(True)
        self.MainStack.addWidget(self.ImportPage)
        self.OperationsPage = QWidget()
        self.OperationsPage.setObjectName(u"OperationsPage")
        self.line_6 = QFrame(self.OperationsPage)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(24, 10, 1162, 20))
        self.line_6.setFrameShadow(QFrame.Plain)
        self.line_6.setLineWidth(5)
        self.line_6.setFrameShape(QFrame.Shape.HLine)
        self.line_7 = QFrame(self.OperationsPage)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(1170, 20, 31, 661))
        self.line_7.setFrameShadow(QFrame.Plain)
        self.line_7.setLineWidth(5)
        self.line_7.setFrameShape(QFrame.Shape.VLine)
        self.line_8 = QFrame(self.OperationsPage)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(24, 670, 1162, 20))
        self.line_8.setFrameShadow(QFrame.Plain)
        self.line_8.setLineWidth(5)
        self.line_8.setFrameShape(QFrame.Shape.HLine)
        self.line_9 = QFrame(self.OperationsPage)
        self.line_9.setObjectName(u"line_9")
        self.line_9.setGeometry(QRect(10, 20, 31, 661))
        self.line_9.setFrameShadow(QFrame.Plain)
        self.line_9.setLineWidth(5)
        self.line_9.setFrameShape(QFrame.Shape.VLine)
        self.widget = QWidget(self.OperationsPage)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(40, 30, 261, 641))
        self.widget.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.label_2 = QLabel(self.widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 10, 261, 71))
        font7 = QFont()
        font7.setFamilies([u"Cascadia Mono"])
        font7.setPointSize(24)
        font7.setBold(True)
        self.label_2.setFont(font7)
        self.label_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_12 = QLabel(self.widget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 60, 261, 71))
        self.label_12.setFont(font7)
        self.label_12.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.widget_2 = QWidget(self.widget)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(0, 180, 261, 80))
        self.widget_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.line_10 = QFrame(self.widget_2)
        self.line_10.setObjectName(u"line_10")
        self.line_10.setGeometry(QRect(10, 2, 236, 20))
        self.line_10.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.line_10.setFrameShadow(QFrame.Plain)
        self.line_10.setLineWidth(5)
        self.line_10.setFrameShape(QFrame.Shape.HLine)
        self.line_11 = QFrame(self.widget_2)
        self.line_11.setObjectName(u"line_11")
        self.line_11.setGeometry(QRect(10, 60, 236, 16))
        self.line_11.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.line_11.setFrameShadow(QFrame.Plain)
        self.line_11.setLineWidth(5)
        self.line_11.setFrameShape(QFrame.Shape.HLine)
        self.line_13 = QFrame(self.widget_2)
        self.line_13.setObjectName(u"line_13")
        self.line_13.setGeometry(QRect(0, 9, 16, 62))
        self.line_13.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.line_13.setFrameShadow(QFrame.Plain)
        self.line_13.setLineWidth(5)
        self.line_13.setFrameShape(QFrame.Shape.VLine)
        self.line_14 = QFrame(self.widget_2)
        self.line_14.setObjectName(u"line_14")
        self.line_14.setGeometry(QRect(241, 9, 16, 62))
        self.line_14.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.line_14.setFrameShadow(QFrame.Plain)
        self.line_14.setLineWidth(5)
        self.line_14.setFrameShape(QFrame.Shape.VLine)
        self.btnMovies = QPushButton(self.widget_2)
        self.btnMovies.setObjectName(u"btnMovies")
        self.btnMovies.setGeometry(QRect(10, 10, 241, 61))
        font8 = QFont()
        font8.setFamilies([u"Cascadia Code"])
        font8.setPointSize(16)
        font8.setBold(True)
        self.btnMovies.setFont(font8)
        self.btnMovies.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btnMovies.setFlat(False)
        self.line_14.raise_()
        self.line_13.raise_()
        self.line_10.raise_()
        self.line_11.raise_()
        self.btnMovies.raise_()
        self.widget_3 = QWidget(self.widget)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setGeometry(QRect(0, 300, 261, 80))
        self.widget_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.line_17 = QFrame(self.widget_3)
        self.line_17.setObjectName(u"line_17")
        self.line_17.setGeometry(QRect(10, 60, 236, 16))
        self.line_17.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.line_17.setFrameShadow(QFrame.Plain)
        self.line_17.setLineWidth(5)
        self.line_17.setFrameShape(QFrame.Shape.HLine)
        self.line_12 = QFrame(self.widget_3)
        self.line_12.setObjectName(u"line_12")
        self.line_12.setGeometry(QRect(10, 2, 236, 20))
        self.line_12.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.line_12.setFrameShadow(QFrame.Plain)
        self.line_12.setLineWidth(5)
        self.line_12.setFrameShape(QFrame.Shape.HLine)
        self.line_15 = QFrame(self.widget_3)
        self.line_15.setObjectName(u"line_15")
        self.line_15.setGeometry(QRect(0, 9, 16, 62))
        self.line_15.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.line_15.setFrameShadow(QFrame.Plain)
        self.line_15.setLineWidth(5)
        self.line_15.setFrameShape(QFrame.Shape.VLine)
        self.line_16 = QFrame(self.widget_3)
        self.line_16.setObjectName(u"line_16")
        self.line_16.setGeometry(QRect(241, 9, 16, 62))
        self.line_16.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.line_16.setFrameShadow(QFrame.Plain)
        self.line_16.setLineWidth(5)
        self.line_16.setFrameShape(QFrame.Shape.VLine)
        self.btnAnime = QPushButton(self.widget_3)
        self.btnAnime.setObjectName(u"btnAnime")
        self.btnAnime.setGeometry(QRect(10, 10, 241, 61))
        self.btnAnime.setFont(font8)
        self.btnAnime.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.btnAnime.setFlat(True)
        self.line_16.raise_()
        self.line_15.raise_()
        self.line_17.raise_()
        self.line_12.raise_()
        self.btnAnime.raise_()
        self.widget_4 = QWidget(self.widget)
        self.widget_4.setObjectName(u"widget_4")
        self.widget_4.setGeometry(QRect(0, 419, 261, 80))
        self.widget_4.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.line_22 = QFrame(self.widget_4)
        self.line_22.setObjectName(u"line_22")
        self.line_22.setGeometry(QRect(10, 2, 236, 20))
        self.line_22.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.line_22.setFrameShadow(QFrame.Plain)
        self.line_22.setLineWidth(5)
        self.line_22.setFrameShape(QFrame.Shape.HLine)
        self.line_23 = QFrame(self.widget_4)
        self.line_23.setObjectName(u"line_23")
        self.line_23.setGeometry(QRect(10, 60, 236, 16))
        self.line_23.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.line_23.setFrameShadow(QFrame.Plain)
        self.line_23.setLineWidth(5)
        self.line_23.setFrameShape(QFrame.Shape.HLine)
        self.line_24 = QFrame(self.widget_4)
        self.line_24.setObjectName(u"line_24")
        self.line_24.setGeometry(QRect(0, 9, 16, 62))
        self.line_24.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.line_24.setFrameShadow(QFrame.Plain)
        self.line_24.setLineWidth(5)
        self.line_24.setFrameShape(QFrame.Shape.VLine)
        self.line_25 = QFrame(self.widget_4)
        self.line_25.setObjectName(u"line_25")
        self.line_25.setGeometry(QRect(241, 9, 16, 62))
        self.line_25.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.line_25.setFrameShadow(QFrame.Plain)
        self.line_25.setLineWidth(5)
        self.line_25.setFrameShape(QFrame.Shape.VLine)
        self.btnCoding = QPushButton(self.widget_4)
        self.btnCoding.setObjectName(u"btnCoding")
        self.btnCoding.setGeometry(QRect(10, 10, 241, 61))
        self.btnCoding.setFont(font8)
        self.btnCoding.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.btnCoding.setFlat(True)
        self.line_25.raise_()
        self.line_24.raise_()
        self.line_22.raise_()
        self.line_23.raise_()
        self.btnCoding.raise_()
        self.widget_5 = QWidget(self.widget)
        self.widget_5.setObjectName(u"widget_5")
        self.widget_5.setGeometry(QRect(0, 530, 261, 80))
        self.widget_5.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.line_27 = QFrame(self.widget_5)
        self.line_27.setObjectName(u"line_27")
        self.line_27.setGeometry(QRect(10, 2, 236, 20))
        self.line_27.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.line_27.setFrameShadow(QFrame.Plain)
        self.line_27.setLineWidth(5)
        self.line_27.setFrameShape(QFrame.Shape.HLine)
        self.line_28 = QFrame(self.widget_5)
        self.line_28.setObjectName(u"line_28")
        self.line_28.setGeometry(QRect(10, 60, 236, 16))
        self.line_28.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.line_28.setFrameShadow(QFrame.Plain)
        self.line_28.setLineWidth(5)
        self.line_28.setFrameShape(QFrame.Shape.HLine)
        self.line_29 = QFrame(self.widget_5)
        self.line_29.setObjectName(u"line_29")
        self.line_29.setGeometry(QRect(0, 9, 16, 62))
        self.line_29.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.line_29.setFrameShadow(QFrame.Plain)
        self.line_29.setLineWidth(5)
        self.line_29.setFrameShape(QFrame.Shape.VLine)
        self.line_30 = QFrame(self.widget_5)
        self.line_30.setObjectName(u"line_30")
        self.line_30.setGeometry(QRect(241, 9, 16, 62))
        self.line_30.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.line_30.setFrameShadow(QFrame.Plain)
        self.line_30.setLineWidth(5)
        self.line_30.setFrameShape(QFrame.Shape.VLine)
        self.btnOverview = QPushButton(self.widget_5)
        self.btnOverview.setObjectName(u"btnOverview")
        self.btnOverview.setGeometry(QRect(10, 10, 241, 61))
        self.btnOverview.setFont(font8)
        self.btnOverview.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.btnOverview.setFlat(True)
        self.line_26 = QFrame(self.OperationsPage)
        self.line_26.setObjectName(u"line_26")
        self.line_26.setGeometry(QRect(300, 20, 31, 661))
        self.line_26.setFrameShadow(QFrame.Plain)
        self.line_26.setLineWidth(5)
        self.line_26.setFrameShape(QFrame.Shape.VLine)
        self.SelectStack = QStackedWidget(self.OperationsPage)
        self.SelectStack.setObjectName(u"SelectStack")
        self.SelectStack.setGeometry(QRect(320, 30, 861, 641))
        self.MoviePage = QWidget()
        self.MoviePage.setObjectName(u"MoviePage")
        self.label_13 = QLabel(self.MoviePage)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(260, 170, 261, 71))
        self.label_13.setFont(font7)
        self.label_13.setStyleSheet(u"color: rgb(0,0,0);")
        self.SelectStack.addWidget(self.MoviePage)
        self.AnimePage = QWidget()
        self.AnimePage.setObjectName(u"AnimePage")
        self.label_14 = QLabel(self.AnimePage)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(500, 260, 261, 71))
        self.label_14.setFont(font7)
        self.label_14.setStyleSheet(u"color: rgb(0,0,0);")
        self.SelectStack.addWidget(self.AnimePage)
        self.CodingPage = QWidget()
        self.CodingPage.setObjectName(u"CodingPage")
        self.label_15 = QLabel(self.CodingPage)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(310, 390, 261, 71))
        self.label_15.setFont(font7)
        self.label_15.setStyleSheet(u"color: rgb(0,0,0);")
        self.SelectStack.addWidget(self.CodingPage)
        self.OverviewPage = QWidget()
        self.OverviewPage.setObjectName(u"OverviewPage")
        self.label_16 = QLabel(self.OverviewPage)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(520, 330, 261, 71))
        self.label_16.setFont(font7)
        self.label_16.setStyleSheet(u"color: rgb(0,0,0);")
        self.SelectStack.addWidget(self.OverviewPage)
        self.MainStack.addWidget(self.OperationsPage)

        self.retranslateUi(TTS)

        self.MainStack.setCurrentIndex(1)
        self.SelectStack.setCurrentIndex(3)


        QMetaObject.connectSlotsByName(TTS)
    # setupUi

    def retranslateUi(self, TTS):
        TTS.setWindowTitle(QCoreApplication.translate("TTS", u"TTS", None))
        self.label.setText(QCoreApplication.translate("TTS", u"Import", None))
        self.label_3.setText(QCoreApplication.translate("TTS", u"Movies/TV Series", None))
        self.btMovieBrowse.setText(QCoreApplication.translate("TTS", u"Browse", None))
        self.chkbxMovies.setText("")
        self.label_4.setText(QCoreApplication.translate("TTS", u"Location:", None))
        self.label_5.setText(QCoreApplication.translate("TTS", u"Anime", None))
        self.btnAnimeBrowse.setText(QCoreApplication.translate("TTS", u"Browse", None))
        self.label_6.setText(QCoreApplication.translate("TTS", u"Location:", None))
        self.chkbxAnime.setText("")
        self.chkbxCoding.setText("")
        self.label_7.setText(QCoreApplication.translate("TTS", u"Coding", None))
        self.btnCodingBrowse.setText(QCoreApplication.translate("TTS", u"Browse", None))
        self.label_8.setText(QCoreApplication.translate("TTS", u"Location:", None))
        self.chkbxLog.setText("")
        self.label_9.setText(QCoreApplication.translate("TTS", u"Previous Log", None))
        self.btnLogBrowse.setText(QCoreApplication.translate("TTS", u"Browse", None))
        self.label_10.setText(QCoreApplication.translate("TTS", u"Location:", None))
        self.btnImport.setText(QCoreApplication.translate("TTS", u"Import", None))
        self.label_11.setText(QCoreApplication.translate("TTS", u"What is previous log ? \n"
"If you have run this software before, the log file \n"
"exported by the software is the previous log,\n"
"You can use this log \n"
"file to import the previously calculated \n"
"data in order to save time.", None))
        self.pushButton.setText("")
        self.pushButton_2.setText("")
        self.pushButton_3.setText("")
        self.label_2.setText(QCoreApplication.translate("TTS", u"TIME TRACK", None))
        self.label_12.setText(QCoreApplication.translate("TTS", u"SUITE", None))
        self.btnMovies.setText(QCoreApplication.translate("TTS", u"Movies", None))
        self.btnAnime.setText(QCoreApplication.translate("TTS", u"Anime", None))
        self.btnCoding.setText(QCoreApplication.translate("TTS", u"Coding", None))
        self.btnOverview.setText(QCoreApplication.translate("TTS", u"Overview", None))
        self.label_13.setText(QCoreApplication.translate("TTS", u"PAGE 1", None))
        self.label_14.setText(QCoreApplication.translate("TTS", u"PAGE 2", None))
        self.label_15.setText(QCoreApplication.translate("TTS", u"PAGE 3", None))
        self.label_16.setText(QCoreApplication.translate("TTS", u"PAGE 4", None))
    # retranslateUi

